# Site
name: ""
title: "Test"
description: "A blog for all things Machine Learning."
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/logo.jpg'
baseurl: 
google_analytics: 'UA-112788446-1'
disqus: 'https-pilatracu-github-io'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  talip:
    name: Talip Ucar
    display_name: Talip Ucar
    gravatar: https://pilatracu.github.io/assets/images/avatar.jpg
    email: pilatracu@gmail.com
    web: 
    twitter: 
    description: ""

  clement:
    name: Clement
    display_name: Clement Wan
    gravatar: https://pilatracu.github.io/assets/images/avatar.jpg
    email: clemento341@gmail.com
    web: 
    twitter: https://twitter.com/cmclementwan
    description: ""
    

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
